# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: echo $CONFIG_JS | base64 --decode > config.js
      - run: echo $SPREADSHEET_READER_SERVICE_ACCOUNT_CREDENTIALS | base64 --decode > credentials.json
      - run: yarn build
      - persist_to_workspace:
          root: dist
          paths:
            - '*'


  deploy:
    docker:
        - image: google/cloud-sdk
    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/dist
      - run: echo $SPREADSHEET_READER_SERVICE_ACCOUNT_CREDENTIALS | base64 --decode > credentials.json
      - run: echo $FROM_CIRCLECI_DEPLOYER_SERICE_ACCOUNT_CREDENTIALS | base64 --decode > ${HOME}/gcloud-service-key.json
      - run: echo $CONFIG_JS | base64 --decode > config.js
      # - run: gcloud --quiet components update
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project $GCLOUD_PROJECT
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: scripts/deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
